boilerplate:
  showImports: true

variables:
  sdkImport: "import com.eulerstream.EulerStreamApiClient;"
  clientConstruction: |
    EulerStreamApiClient client = EulerStreamApiClient.builder()
        .basePath("$baseUrl")
        .apiKey("$apiKey")
        .build();
  clientVar: client
  apiAccessPattern: call

templatePath: ./wrapper.mustache

outputFormats:
  - md
  - json

apiClassMap:
  "TikTok LIVE": webcast
  "TikTok LIVE Premium": premium
  "TikTok LIVE Moderation": moderation
  "TikTok General": general
  "TikTok Captchas": captchas
  Analytics: analytics
  "TikTok LIVE Alerts": alerts
  "TikTok LIVE Alert Targets": alertTargets
  Accounts: accounts
  Authentication: authentication

paramOverrides:
  global:
    account_id: $accountId

excludeParams:
  - x-cookie-header
